---
title: "Test Rmd File"
author: "Daniel Allington"
date: "2026-02-10"
output: html_document
---

In this Rmd file, we develop and test basic bits of code.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(dplyr)
library(purrr)
library(reshape2)
library(ggplot2)
```

```{r}
population.p <- .1
population.N <- 10000

population <- c(
  rep(1, population.N * population.p), 
  rep(0, population.N * (1 - population.p)))
```

Bib ref for complement function:

@MISC {313138,
    TITLE = {Generate a random variable with a defined correlation to an existing variable(s)},
    AUTHOR = {whuber (https://stats.stackexchange.com/users/919/whuber)},
    HOWPUBLISHED = {Cross Validated},
    NOTE = {URL:https://stats.stackexchange.com/q/313138 (version: 2021-01-14)},
    EPRINT = {https://stats.stackexchange.com/q/313138},
    URL = {https://stats.stackexchange.com/q/313138}
}

```{r}
sample.size <- 1000

complement <- function(x, rho) {
  y <- rnorm(length(x))
  x.perp <- residuals(lm(y ~ x))
  rho * sd(x.perp) * x + x.perp * sd(y) * sqrt(1 - rho^2)
}

take.sample <- function(x, n, data.defect.correlation) {
  proportion.to.sample <- n / length(x)
  y <- complement(x, data.defect.correlation * 2)
  sampling.p <- ecdf(y)(y) * proportion.to.sample * 2
  sample(x, size = n, replace = FALSE, prob = sampling.p)
}

samples <- (1:10) %>%
  map_dbl(
    function(x) {
      mean(take.sample(population, sample.size, 0.15))
    }
  )
```

```{r}
prop.ci <- function(p, n, conf.level) {
  conf.level <- conf.level %>% as.character
  critical.values <- c('0.90' = 1.645, '0.95' = 1.96, '0.99' = 2.575)
  if(!conf.level %in% names(critical.values)) {
    stop(paste('Acceptable confidence levels:', paste(names(critical.values), collapse = ', ')))
  }
  moe <- critical.values[conf.level] * sqrt(p * (1 - p) / n)
  tibble(Low = p - moe, High = p + moe)
}

justmid <- function(d) {
  d %>%
    summarise(
      Mid = mean(p)
    )
}

minmax <- function(d) {
  d %>%
    summarise(
      Low = min(p),
      High = max(p)
    )
}

sdrange <- function(d) {
  d %>%
    summarise(
      Low = mean(p) - sd(p),
      High = mean(p) + sd(p)
    )
}

visualise.samples <- function(
    d, 
    include.mean = FALSE, 
    population.line = FALSE,
    range.function = NULL,
    confint = NULL) {
  
  d <- d %>%
    mutate(
      Sample = factor(
        Sample,
        levels = c(
          'Pop.', d$Sample[d$Sample!='Pop.']) %>% rev
      ),
      Colour = ifelse(
        Sample == 'Pop.',
        'Pop.', 'Sample'
      )
    )
  
  if(include.mean) {
    d.sample.summary <- d %>%
      filter(
        Sample != 'Pop.'
      ) %>%
      summarise(Mid = mean(p)) %>%
      melt(id = NULL, variable.name = 'Statistic', value.name = 'Value')
  } else {
    d.sample.summary <- tibble(
      Statistics = character(), Value = numeric()
    )
  }

  if(!is.null(range.function)) {
    d.sample.summary <- d %>%
      filter(
        Sample != 'Pop.'
      ) %>%
      range.function %>%
      melt(id = NULL, variable.name = 'Statistic', value.name = 'Value') %>%
      rbind(
        d.sample.summary
      )
  }
  
  p <- d %>%
    ggplot(
      aes(x = Sample, y = p, colour = Colour, fill = Colour)
    ) +
    geom_col()
  
  if(population.line) {
    p <- p +
      geom_hline(
        yintercept = d$p[d$Sample=='Pop.'],
        linetype = 'dashed',
        linewidth = 1,
        colour = 'darkred'
      )
  }
  
  if(!is.null(confint)) {
    p <- p +
      geom_errorbar(
        aes(
          ymin = Low,
          ymax = High
        ),
        data = tibble(d, prop.ci(d$p, d$n, confint)),
        width = 0.25
      )
  }
  
  if(nrow(d.sample.summary) > 0) {
    p <- p +
      geom_hline(
        aes(yintercept = Value, linetype = Statistic),
        linewidth = 1,
        data = d.sample.summary
      ) +
      scale_linetype_manual(
        values = c(
          Low = 'dotted', Mid = 'dotdash', High = 'dotted'), guide = 'none')
  }
  
  p +
    scale_x_discrete(
      '') +
    scale_y_continuous(
      '', limits = c(0,1), labels = scales::percent) +
    scale_colour_manual(
      values = c(
        'Pop.' = 'darkred', 'Sample' = 'darkblue'), guide = 'none') +
    scale_fill_manual(
      values = c(
        'Pop.' = 'pink', 'Sample' = 'lightblue'), guide = 'none') +
    coord_flip() +
    theme_bw()
}

tibble(
  Sample = c('Pop.', 1:length(samples)), 
  n = c(NA, rep(sample.size, length(samples))),
  p = c(mean(population), samples)
  ) %>%
  visualise.samples(
    include.mean = TRUE, population.line = TRUE, range.function = sdrange, confint = .95)
```

